"""Export an assembled publication as a static site for a CDN host (Netlify), with media served elsewhere.

    python web/classic/export_static.py --publication /absolute/publication --out /absolute/static \
        --site-url https://keygen-bench.netlify.app --media-map /absolute/media-map.json

The publication is build.py's output (index.html, app.js, site.js, core/, dist/ with og/ from build_og.py).
`--media-map` is a JSON object mapping each media file name to its absolute URL (MP3 and XM renders, and a
lossless FLAC loop source per WAV, keyed by the FLAC name). data.json's media paths are rewritten to those
URLs, so dist/media/ is not copied; dist/evaluations/ is not read by the site and is dropped; each run's
playback trace moves to dist/traces/<slug>.json, loaded when the tracker opens the run. Every route in dist/og/meta.json gets its own index.html with that
route's preview tags (static hosts cannot inject them per request); other app routes fall back to the
root index.html through netlify.toml. Files are hard-linked where possible; the output must not exist.
"""
import argparse
import json
import os
import shutil
from pathlib import Path

from serve import APP_ROUTES, with_og

STATIC_HEADERS = """
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/core/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/core/ft2gfx/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
"""


def media_url(path: str, mapping: dict, kind: str) -> str:
    name = Path(path).name
    if kind == "wav":
        name = Path(name).with_suffix(".flac").name
    if name not in mapping:
        raise ValueError(f"No hosted URL for {name}")
    return mapping[name]


def link_or_copy(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(source, target)
    except OSError:
        shutil.copy2(source, target)


def export(publication: Path, out: Path, site_url: str, mapping: dict, redirect_from: list[str] = ()) -> None:
    if out.exists():
        raise ValueError("Use a new output directory")
    site_url = site_url.rstrip("/")
    for path in publication.rglob("*"):
        rel = path.relative_to(publication)
        if path.is_symlink():
            raise ValueError(f"{rel}: public files must not be symlinks")
        # dist/media is hosted elsewhere; dist/evaluations (full evaluation records) is not read by the site.
        if (path.is_file() and rel.parts[:2] not in (("dist", "media"), ("dist", "evaluations"))
                and rel != Path("dist/data.json") and "__pycache__" not in rel.parts):
            link_or_copy(path, out / rel)
    data = json.loads((publication / "dist/data.json").read_text())
    traces = out / "dist/traces"
    traces.mkdir(parents=True)
    for run in data["runs"]:
        media = run.get("media") or {}
        media.pop("evaluation", None)
        for kind in ("xm", "audio", "wav"):
            if media.get(kind):
                media[kind] = media_url(media[kind], mapping, kind)
        # Playback traces are ~70% of data.json and only the tracker needs them: one file per run, loaded on open.
        if run.get("trace") is not None:
            (traces / f"{run['slug']}.json").write_text(json.dumps(run.pop("trace"), separators=(",", ":")) + "\n")
            media["trace"] = f"traces/{run['slug']}.json"
    (out / "dist/data.json").write_text(json.dumps(data, separators=(",", ":"), allow_nan=False) + "\n")
    meta = json.loads((publication / "dist/og/meta.json").read_text())
    shell = (publication / "index.html").read_text(encoding="utf-8")
    (out / "index.html").unlink()
    for route in meta:
        # "/tracker/x" -> tracker/x.html: Netlify serves it at the bare path (a directory index would 301 to "/tracker/x/").
        target = out / (route.strip("/") + ".html") if route != "/" else out / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(with_og(shell, meta, route, site_url), encoding="utf-8")
    redirects = "\n".join(f'[[redirects]]\n  from = "/{route}/*"\n  to = "/index.html"\n  status = 200\n'
                          for route in sorted(APP_ROUTES))
    # Other hostnames of the same deployment (e.g. the *.netlify.app default) move permanently to --site-url.
    canonical = "".join(f'[[redirects]]\n  from = "https://{host}/*"\n  to = "{site_url}/:splat"\n  status = 301\n  force = true\n\n'
                        for host in redirect_from)
    (out / "netlify.toml").write_text(f"# Generated by web/classic/export_static.py\n\n{canonical}{redirects}{STATIC_HEADERS}")
    print(f"{len(meta)} routes with preview tags, {len(data['runs'])} runs with hosted media -> {out}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--publication", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--site-url", required=True, help="Public origin used in og:url and og:image")
    parser.add_argument("--media-map", type=Path, required=True)
    parser.add_argument("--redirect-from", action="append", default=[], metavar="HOST",
                        help="Another hostname of this deployment to redirect permanently to --site-url")
    args = parser.parse_args()
    export(args.publication.resolve(), args.out.resolve(), args.site_url, json.loads(args.media_map.read_text()), args.redirect_from)
